// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf4Hz3LpI8-mu8Nk-8ThHOuSAWRFOmWMQ',
    appId: '1:907158091238:web:d85ecad4579f30b2c55227',
    messagingSenderId: '907158091238',
    projectId: 'fooders-f9f59',
    authDomain: 'fooders-f9f59.firebaseapp.com',
    storageBucket: 'fooders-f9f59.appspot.com',
    measurementId: 'G-CJWY3S4P3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVOA29GpX5e8sQf9l2sEnv_IgxD_ioJro',
    appId: '1:907158091238:android:23164ca8feb3f3a3c55227',
    messagingSenderId: '907158091238',
    projectId: 'fooders-f9f59',
    storageBucket: 'fooders-f9f59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjmwbTvxKMrjtLCNn_2SwQALMcfkJr7_4',
    appId: '1:907158091238:ios:c72b939513eed504c55227',
    messagingSenderId: '907158091238',
    projectId: 'fooders-f9f59',
    storageBucket: 'fooders-f9f59.appspot.com',
    iosClientId: '907158091238-cj4tfm0aok3a86k43sl0f5ne2dnrooft.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );
}
